### ISSUE TITLE
Noob-proof the installation instructions

### ISSUE THREAD

**Issue by marblegravy** [fubarhouse/dvm#92]
The installation instructions aren't clear for noob go users (like me) at the moment.

I'd suggest the instructions should be more specific:

Build a version of DVM:
`go get -u github.com/fubarhouse/dvm/cmd/dvm`

Ensure DVM is in the PATH so you can run the other statements:
`export PATH=$PATH:$(go env GOPATH)/bin`

Also - installation **option 3** in the current readme says to download the precompiled binaries, but unless I'm looking in the wrong place, I can't see where the precompiled binaries can be downloaded from?

**Comment by fubarhouse** [comment]
@marblegravy,

It is assumed that when a user is using `go get`, that the $PATH has been configured to include $GOBIN or $GOPATH, but I will make that clearer.

Also, [precompiled binaries](https://github.com/fubarhouse/dvm/releases) are a part of the release for this project on the releases page. They are produced with [gox](https://github.com/mitchellh/gox). They *do not* include windows builds, which may change at some point, and they should be placed inside any path included in $PATH such as /usr/local/bin/dvm or /usr/bin/dvm and they will require rights to execute.

I'll let you know once a PR is ready so you can have a look and provide feedback before a new release.

**Comment by marblegravy** [comment]
Ah OK, for Option 3, perhaps link through to the releases page from the readme then to make that clearer?
```
* Download the (pre-compiled binaries)[https://github.com/fubarhouse/dvm/releases].
* Copy to location in $PATH environment variable.
```

**Comment by fubarhouse** [comment]
Please review the following when you can; 2.3.0 is released.
* https://github.com/fubarhouse/dvm/tree/dev-2.x

**Comment by marblegravy** [comment]
Pull request made: #99

**Comment by fubarhouse** [comment]
Merged!

I might do some more work to the readme before the next release - the framework and all the associated changes basically make the usage documentation superseded.

**Comment by fubarhouse** [comment]
So the readme is all spick and span.

If you've nothing to add within the next week, I'll close this off.

**Comment by marblegravy** [comment]
I'm sure there are other improvements that can be made, but it's better
now. Close away.
