### ISSUE TITLE
Trigger help text when no parameters sent

### ISSUE THREAD

**Issue by marblegravy** [fubarhouse/dvm#94]
Can you configure things to trigger help text when incorrect or no parameters are submitted?

Right now the dvm command on it's own triggers the following error:

`$ dvm
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xd0740, 0xc42000c0e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/Users/contagious/Code/go/src/github.com/fubarhouse/dvm/cmd/dvm/main.go:36 +0xa70`

Line 36 is:
`			if os.Args[1] != "install" && os.Args[1] != "reinstall" && os.Args[1] != "use" {`

so I imagine it's triupping over the fact that os.Args[1] doesn't exist. On the previous line, there's checkto see if the args <2 but doesn't check for length of zero:

`		if len(os.Args) < 2 {`

suggest that this may just need an additional check:

`		if len(os.Args) < 2 && len(os.Args) >0 {`

Would that fix the issue allowing the script to fall through to trigger the print_usage() call?

**Comment by fubarhouse** [comment]
This is pretty high on the to-do list, but I'll update this as progress is made.

**Comment by fubarhouse** [comment]
Please review the following when you can; 2.3.0 is released.
* https://github.com/fubarhouse/dvm/tree/dev-2.x

**Comment by fubarhouse** [comment]
Some testing from another system has proven this is still a problem - despite the other fixes which have significantly improved all other circumstances...

I'll release the new changes tonight.

**Comment by fubarhouse** [comment]
The upcoming release (dev-2.x) supports the Cobra framework (#96).

Could you please review this one, if nothing is raised before the next release I'll close this off.

**Comment by marblegravy** [comment]
This is now working well, but the help text isn't enough to get someone started.

Example:
```
| => dvm help
Drush Version Manager

A command-line tool to quickly and efficiently manage
multiple Drush versions from a single symlink.

Usage:
  dvm [command]

Available Commands:
  help        Help about any command
  install     Install a specific version of Drush
  list        List available or installed Drush versions.
  reinstall   Reinstall a specific version of Drush
  uninstall   Uninstall a specific version of Drush
  use         Initialise or replace an established symlink to the configured location, for a given version of Drush

Flags:
      --config string   config file (default is $HOME/config.toml)
  -h, --help            help for dvm
  -t, --toggle          Help message for toggle

Use "dvm [command] --help" for more information about a command.
________________________________________________________________________________
| => dvm install
FATA[0000] expected 1 argument, 0 found
```

The help wasn't enough to tell me what else I need to add to the ```dvm install``` command.

Following noob logic, I then tried to get help on the individual commands:

```
| => dvm install -h
Install a specific version of Drush

Usage:
  dvm install [flags]

Flags:
  -h, --help   help for install

Global Flags:
      --config string   config file (default is $HOME/config.toml)
```

But still not enough info. I'd suggest maybe including a basic example of the most common commands? Or describe what valid values for [flags] might be?

**Comment by marblegravy** [comment]
The examples from the readme would be excellent candidates for being included in the help text...

**Comment by fubarhouse** [comment]
As that text is all default from the cobra framework, I'm looking into it now.

**Comment by fubarhouse** [comment]
This is done.

If you do not provide any further feedback for action within the next week, I'll close this off.
